doctrine:
    dbal:
#        connections:
#            clickhouse:
#                host:     db_no_sql
#                port:     8123
#                user:     default
#                password: ""
#                dbname:   market
#                driver_class: FOD\DBALClickHouse\Driver
#                wrapper_class: FOD\DBALClickHouse\Connection
#                auto_commit: false
#                options:
#                  enable_http_compression: 1
#                  max_execution_time: 60
        #        url: '%env(resolve:DATABASE_URL)%'

                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_composer require friendsofdoctrine/dbal-clickhouseURL env var (see .env file)
        #        server_version: '12'
        dbname: market
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
